name: HiPhase MiniWDL
description: "Phase VCFs and haplotag BAMs with HiPhase"

agent_requirements:
  cpu_cores: 24
  memory_gb: 96

parameters:
  - name: sample_id
    label: Sample ID
    type: string
    help: "Sample ID"
    
  - name: aligned_bam
    label: Aligned BAM
    type: file
    pattern_match:
      - "*.bam"
    help: "Aligned BAM file"
    
  - name: output_folder
    label: Output Folder
    type: directory
    supports_location_mode: 'no_append'
    
  - name: cache_udocker_images
    label: Cache Udocker Image
    type: boolean
    value: true

steps:
  - name: hiphase
    type: cmd
    description: "Phase VCFs and haplotag BAMs with HiPhase"
    args:
      - |- # shell
        set -eu pipefail

        # Set up resource path
        PB_RESOURCES_DIR="${WORKSPACE_DIR}/${RESOURCES_PATH}/hifi-wdl-resources-v3.0.0"
        # TASK_NAME=$(basename "$(dirname "$(dirname "$(dirname "$(dirname "$PWD")")")")")

        # Function to handle miniwdl failure
        handle_miniwdl_failure() {
          local exit_code=$1
          echo "MiniWDL run failed with exit code $exit_code"
          echo "Capturing debug information..."
          bash "$TASK_DIR/miniwdl-debug-capture.sh" /scratch/_LAST "$output_folder" "$TASK_NAME"
          exit $exit_code
        }

        # Set environment variables for miniwdl
        export MINIWDL__SCHEDULER__CONTAINER_BACKEND=udocker
        export MINIWDL__FILE_IO__ALLOW_ANY_INPUT=true
        export MINIWDL__SCHEDULER__TASK_CONCURRENCY=8
        # export UDOCKER_SET_EXECUTION_MODE=F4
        export UDOCKER_DIR=/scratch/.udocker
        
        # Set up reference files (hardcoded from ref_map)
        REF_FASTA="${PB_RESOURCES_DIR}/GRCh38/human_GRCh38_no_alt_analysis_set.fasta"
        REF_INDEX="${PB_RESOURCES_DIR}/GRCh38/human_GRCh38_no_alt_analysis_set.fasta.fai"
        REF_NAME="GRCh38"

        # Find index files
        aligned_bam_index="${aligned_bam}.bai"

        # Infer VCF files from upstream tasks
        # Small variant VCF from DeepVariant
        small_variant_vcf=$(echo "${aligned_bam}" | cut -d '.' -f 1).small_variants.vcf.gz
        small_variant_vcf_index="${small_variant_vcf}.tbi"
        
        # SV VCF from Sawfish
        sv_vcf=$(echo "${aligned_bam}" | cut -d '.' -f 1).structural_variants.vcf.gz
        sv_vcf_index="${sv_vcf}.tbi"
        
        # TRGT VCF from TRGT
        trgt_vcf=$(echo "${aligned_bam}" | cut -d '.' -f 1).trgt.sorted.vcf.gz
        trgt_vcf_index="${trgt_vcf}.tbi"

        # Verify reference files exist
        if [ ! -f "$REF_FASTA" ]; then
          echo "Error: Reference FASTA file not found at $REF_FASTA"
          echo "Please ensure the PacBio WDL resources have been downloaded using the Download PacBio Reference Data Resources task"
          exit 1
        fi

        if [ ! -f "$REF_INDEX" ]; then
          echo "Error: Reference FASTA index file not found at $REF_INDEX"
          echo "Please ensure the PacBio WDL resources have been downloaded using the Download PacBio Reference Data Resources task"
          exit 1
        fi
        
        # Pull udocker layers from cache if requested
        if [ -d "${WORKSPACE_DIR}/${RESOURCES_PATH}/udocker_cache/${TASK_NAME}" ]; then
          echo "Pulling udocker image from cache..."
          mkdir -p /scratch/.udocker
          cp -R "${WORKSPACE_DIR}/${RESOURCES_PATH}/udocker_cache/${TASK_NAME}"/* /scratch/.udocker/ || \
            { echo "Failed to copy udocker cache to /scratch/.udocker; will pull layers instead"; }
        fi
        
        # Check for required input files
        if [ ! -f "$aligned_bam" ]; then
          echo "Error: Aligned BAM file not found at $aligned_bam"
          exit 1
        fi
        
        if [ ! -f "$aligned_bam_index" ]; then
          echo "Error: BAM index file not found at $aligned_bam_index"
          exit 1
        fi

        # Check for VCF files
        if [ ! -f "$small_variant_vcf" ]; then
          echo "Error: Small variant VCF file not found at $small_variant_vcf"
          echo "Please ensure DeepVariant has been run on this sample"
          exit 1
        fi
        
        if [ ! -f "$small_variant_vcf_index" ]; then
          echo "Error: Small variant VCF index file not found at $small_variant_vcf_index"
          exit 1
        fi
        
        if [ ! -f "$sv_vcf" ]; then
          echo "Error: Structural variant VCF file not found at $sv_vcf"
          echo "Please ensure Sawfish has been run on this sample"
          exit 1
        fi
        
        if [ ! -f "$sv_vcf_index" ]; then
          echo "Error: Structural variant VCF index file not found at $sv_vcf_index"
          exit 1
        fi
        
        if [ ! -f "$trgt_vcf" ]; then
          echo "Error: TRGT VCF file not found at $trgt_vcf"
          echo "Please ensure TRGT has been run on this sample"
          exit 1
        fi
        
        if [ ! -f "$trgt_vcf_index" ]; then
          echo "Error: TRGT VCF index file not found at $trgt_vcf_index"
          exit 1
        fi

        # Copy input files to /scratch
        echo "Copying input files to /scratch..."
        cp "${aligned_bam}" /scratch/
        cp "$aligned_bam_index" /scratch/
        cp "$small_variant_vcf" /scratch/
        cp "$small_variant_vcf_index" /scratch/
        cp "$sv_vcf" /scratch/
        cp "$sv_vcf_index" /scratch/
        cp "$trgt_vcf" /scratch/
        cp "$trgt_vcf_index" /scratch/
        
        # Copy reference files to /scratch
        echo "Copying reference files to /scratch..."
        cp "$REF_FASTA" /scratch/
        cp "$REF_INDEX" /scratch/
        
        # Set local file paths
        LOCAL_BAM="/scratch/$(basename "${aligned_bam}")"
        LOCAL_BAM_INDEX="/scratch/$(basename "${aligned_bam_index}")"
        LOCAL_REF_FASTA="/scratch/$(basename "$REF_FASTA")"
        LOCAL_REF_INDEX="/scratch/$(basename "$REF_INDEX")"
        LOCAL_SMALL_VARIANT_VCF="/scratch/$(basename "${small_variant_vcf}")"
        LOCAL_SMALL_VARIANT_VCF_INDEX="/scratch/$(basename "${small_variant_vcf_index}")"
        LOCAL_SV_VCF="/scratch/$(basename "${sv_vcf}")"
        LOCAL_SV_VCF_INDEX="/scratch/$(basename "${sv_vcf_index}")"
        LOCAL_TRGT_VCF="/scratch/$(basename "${trgt_vcf}")"
        LOCAL_TRGT_VCF_INDEX="/scratch/$(basename "${trgt_vcf_index}")"

        # Generate phased VCF names (matching downstream.wdl line 83)
        PHASED_SMALL_VARIANT_VCF_NAME="$(basename "${small_variant_vcf}" .vcf.gz).phased.vcf.gz"
        PHASED_SV_VCF_NAME="$(basename "${sv_vcf}" .vcf.gz).phased.vcf.gz"
        PHASED_TRGT_VCF_NAME="$(basename "${trgt_vcf}" .vcf.gz).phased.vcf.gz"
        
        # Generate phased VCF index names
        PHASED_SMALL_VARIANT_VCF_INDEX_NAME="$(basename "${small_variant_vcf_index}" .vcf.gz.tbi).phased.vcf.gz.tbi"
        PHASED_SV_VCF_INDEX_NAME="$(basename "${sv_vcf_index}" .vcf.gz.tbi).phased.vcf.gz.tbi"
        PHASED_TRGT_VCF_INDEX_NAME="$(basename "${trgt_vcf_index}" .vcf.gz.tbi).phased.vcf.gz.tbi"

        # Create JSON structure for hiphase inputs
        cat > /scratch/hiphase_inputs.json << EOF
        {
          "hiphase.sample_id": "$sample_id",
          "hiphase.vcfs": ["$LOCAL_SMALL_VARIANT_VCF", "$LOCAL_SV_VCF", "$LOCAL_TRGT_VCF"],
          "hiphase.vcf_indices": ["$LOCAL_SMALL_VARIANT_VCF_INDEX", "$LOCAL_SV_VCF_INDEX", "$LOCAL_TRGT_VCF_INDEX"],
          "hiphase.phased_vcf_names": ["$PHASED_SMALL_VARIANT_VCF_NAME", "$PHASED_SV_VCF_NAME", "$PHASED_TRGT_VCF_NAME"],
          "hiphase.phased_vcf_index_names": ["$PHASED_SMALL_VARIANT_VCF_INDEX_NAME", "$PHASED_SV_VCF_INDEX_NAME", "$PHASED_TRGT_VCF_INDEX_NAME"],
          "hiphase.aligned_bam": "$LOCAL_BAM",
          "hiphase.aligned_bam_index": "$LOCAL_BAM_INDEX",
          "hiphase.ref_name": "$REF_NAME",
          "hiphase.ref_fasta": "$LOCAL_REF_FASTA",
          "hiphase.ref_index": "$LOCAL_REF_INDEX",
          "hiphase.runtime_attributes": {
            "backend": "HPC",
            "preemptible_tries": 0,
            "max_retries": 1,
            "zones": "",
            "cpuPlatform": "",
            "gpuType": "",
            "container_registry": "quay.io/pacbio"
          }
        }
        EOF
        cat /scratch/hiphase_inputs.json

        # Run hiphase with miniwdl
        echo "Running HiPhase..."
        set +e
        miniwdl run \
          --task hiphase \
          "${TASK_DIR}/wdl/wdl-common/wdl/tasks/hiphase.wdl" \
          --dir /scratch \
          --runtime-cpu-max=$AGENT_CPU_CORES \
          --runtime-memory-max=${AGENT_MEMORY_GB}G \
          -i /scratch/hiphase_inputs.json
        HIPHASE_EXIT_CODE=$?
        set -e

        if [ $HIPHASE_EXIT_CODE -ne 0 ]; then
          echo "HiPhase failed with exit code $HIPHASE_EXIT_CODE"
          handle_miniwdl_failure $HIPHASE_EXIT_CODE
        fi

        echo "HiPhase completed successfully"
        bash "$TASK_DIR/process-outputs.sh" "$output_folder" "${sample_id}" 
        
        # Copy udocker cache to output folder
        if [ "$cache_udocker_images" = true ] && [ ! -d "${WORKSPACE_DIR}/${RESOURCES_PATH}/udocker_cache/${TASK_NAME}" ]; then
          echo "Copying udocker cache to resources folder..."
          mkdir -p "${WORKSPACE_DIR}/${RESOURCES_PATH}/udocker_cache/${TASK_NAME}"
          cp -r /scratch/.udocker/layers /scratch/.udocker/repos "${WORKSPACE_DIR}/${RESOURCES_PATH}/udocker_cache/${TASK_NAME}" 2>/dev/null || true
        fi

        echo "HiPhase VCF phasing and BAM haplotagging completed successfully"
        echo "Output files copied to: $output_folder" 
        